/********************************************************************************
** Form generated from reading UI file 'clientdetailinfo.ui'
**
** Created by: Qt User Interface Compiler version 5.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CLIENTDETAILINFO_H
#define UI_CLIENTDETAILINFO_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ClientDetailInfo
{
public:
    QGroupBox *groupBox_41;
    QGroupBox *groupBox_43;
    QTableWidget *tableWidget_RbClockStatus_2;
    QGroupBox *groupBox_44;
    QTableWidget *tableWidget_cardBoardStatus_2;
    QGroupBox *groupBox_45;
    QLabel *label_13;
    QLabel *label_14;
    QLineEdit *lineEdit_powerStatus_2;
    QLineEdit *lineEdit_powerOrigin_2;
    QGroupBox *groupBox_42;
    QTableWidget *tableWidget_timeRespurce_4;
    QGroupBox *groupBox_31;
    QGroupBox *groupBox_27;
    QTableWidget *tableWidget_timeRespurce_3;
    QGroupBox *groupBox_32;
    QTableWidget *tableWidget_RbClockStatus_1;
    QGroupBox *groupBox_40;
    QTableWidget *tableWidget_cardBoardStatus_1;
    QGroupBox *groupBox_39;
    QLabel *label_11;
    QLabel *label_12;
    QLineEdit *lineEdit_powerStatus_1;
    QLineEdit *lineEdit_powerOrigin_1;
    QPushButton *pushButton;
    QLabel *label;

    void setupUi(QWidget *ClientDetailInfo)
    {
        if (ClientDetailInfo->objectName().isEmpty())
            ClientDetailInfo->setObjectName(QStringLiteral("ClientDetailInfo"));
        ClientDetailInfo->resize(1024, 649);
        groupBox_41 = new QGroupBox(ClientDetailInfo);
        groupBox_41->setObjectName(QStringLiteral("groupBox_41"));
        groupBox_41->setGeometry(QRect(530, 30, 461, 611));
        groupBox_43 = new QGroupBox(groupBox_41);
        groupBox_43->setObjectName(QStringLiteral("groupBox_43"));
        groupBox_43->setGeometry(QRect(20, 310, 431, 171));
        tableWidget_RbClockStatus_2 = new QTableWidget(groupBox_43);
        if (tableWidget_RbClockStatus_2->columnCount() < 3)
            tableWidget_RbClockStatus_2->setColumnCount(3);
        QFont font;
        font.setFamily(QString::fromUtf8("\345\256\213\344\275\223"));
        font.setPointSize(12);
        font.setBold(true);
        font.setWeight(75);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        __qtablewidgetitem->setFont(font);
        tableWidget_RbClockStatus_2->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        __qtablewidgetitem1->setFont(font);
        tableWidget_RbClockStatus_2->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        __qtablewidgetitem2->setFont(font);
        tableWidget_RbClockStatus_2->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        if (tableWidget_RbClockStatus_2->rowCount() < 4)
            tableWidget_RbClockStatus_2->setRowCount(4);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidget_RbClockStatus_2->setVerticalHeaderItem(0, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidget_RbClockStatus_2->setVerticalHeaderItem(1, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidget_RbClockStatus_2->setVerticalHeaderItem(2, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidget_RbClockStatus_2->setVerticalHeaderItem(3, __qtablewidgetitem6);
        QFont font1;
        font1.setFamily(QString::fromUtf8("\345\256\213\344\275\223"));
        font1.setPointSize(11);
        font1.setBold(true);
        font1.setWeight(75);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        __qtablewidgetitem7->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem7->setFont(font1);
        tableWidget_RbClockStatus_2->setItem(0, 0, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidget_RbClockStatus_2->setItem(0, 1, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidget_RbClockStatus_2->setItem(0, 2, __qtablewidgetitem9);
        QFont font2;
        font2.setPointSize(11);
        font2.setBold(true);
        font2.setWeight(75);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        __qtablewidgetitem10->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem10->setFont(font2);
        tableWidget_RbClockStatus_2->setItem(1, 0, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidget_RbClockStatus_2->setItem(1, 1, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableWidget_RbClockStatus_2->setItem(1, 2, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        __qtablewidgetitem13->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem13->setFont(font1);
        tableWidget_RbClockStatus_2->setItem(2, 0, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableWidget_RbClockStatus_2->setItem(2, 1, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWidget_RbClockStatus_2->setItem(2, 2, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        __qtablewidgetitem16->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem16->setFont(font1);
        tableWidget_RbClockStatus_2->setItem(3, 0, __qtablewidgetitem16);
        tableWidget_RbClockStatus_2->setObjectName(QStringLiteral("tableWidget_RbClockStatus_2"));
        tableWidget_RbClockStatus_2->setGeometry(QRect(6, 20, 421, 148));
        tableWidget_RbClockStatus_2->horizontalHeader()->setCascadingSectionResizes(true);
        tableWidget_RbClockStatus_2->horizontalHeader()->setDefaultSectionSize(139);
        tableWidget_RbClockStatus_2->verticalHeader()->setVisible(false);
        tableWidget_RbClockStatus_2->verticalHeader()->setCascadingSectionResizes(false);
        tableWidget_RbClockStatus_2->verticalHeader()->setHighlightSections(false);
        groupBox_44 = new QGroupBox(groupBox_41);
        groupBox_44->setObjectName(QStringLiteral("groupBox_44"));
        groupBox_44->setGeometry(QRect(20, 490, 431, 111));
        tableWidget_cardBoardStatus_2 = new QTableWidget(groupBox_44);
        if (tableWidget_cardBoardStatus_2->columnCount() < 3)
            tableWidget_cardBoardStatus_2->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        __qtablewidgetitem17->setFont(font);
        tableWidget_cardBoardStatus_2->setHorizontalHeaderItem(0, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        __qtablewidgetitem18->setFont(font);
        tableWidget_cardBoardStatus_2->setHorizontalHeaderItem(1, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        __qtablewidgetitem19->setFont(font);
        tableWidget_cardBoardStatus_2->setHorizontalHeaderItem(2, __qtablewidgetitem19);
        if (tableWidget_cardBoardStatus_2->rowCount() < 2)
            tableWidget_cardBoardStatus_2->setRowCount(2);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tableWidget_cardBoardStatus_2->setVerticalHeaderItem(0, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tableWidget_cardBoardStatus_2->setVerticalHeaderItem(1, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        __qtablewidgetitem22->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem22->setFont(font1);
        tableWidget_cardBoardStatus_2->setItem(0, 0, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        tableWidget_cardBoardStatus_2->setItem(0, 1, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        tableWidget_cardBoardStatus_2->setItem(0, 2, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        __qtablewidgetitem25->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem25->setFont(font1);
        tableWidget_cardBoardStatus_2->setItem(1, 0, __qtablewidgetitem25);
        tableWidget_cardBoardStatus_2->setObjectName(QStringLiteral("tableWidget_cardBoardStatus_2"));
        tableWidget_cardBoardStatus_2->setGeometry(QRect(6, 20, 421, 88));
        tableWidget_cardBoardStatus_2->horizontalHeader()->setDefaultSectionSize(139);
        tableWidget_cardBoardStatus_2->verticalHeader()->setVisible(false);
        groupBox_45 = new QGroupBox(groupBox_41);
        groupBox_45->setObjectName(QStringLiteral("groupBox_45"));
        groupBox_45->setGeometry(QRect(20, 20, 431, 61));
        label_13 = new QLabel(groupBox_45);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(70, 7, 111, 21));
        label_13->setFont(font1);
        label_13->setTextFormat(Qt::AutoText);
        label_13->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_14 = new QLabel(groupBox_45);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(70, 34, 111, 21));
        label_14->setFont(font1);
        label_14->setTextFormat(Qt::AutoText);
        label_14->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEdit_powerStatus_2 = new QLineEdit(groupBox_45);
        lineEdit_powerStatus_2->setObjectName(QStringLiteral("lineEdit_powerStatus_2"));
        lineEdit_powerStatus_2->setGeometry(QRect(180, 7, 113, 20));
        QFont font3;
        font3.setFamily(QString::fromUtf8("\345\256\213\344\275\223"));
        lineEdit_powerStatus_2->setFont(font3);
        lineEdit_powerStatus_2->setAlignment(Qt::AlignCenter);
        lineEdit_powerOrigin_2 = new QLineEdit(groupBox_45);
        lineEdit_powerOrigin_2->setObjectName(QStringLiteral("lineEdit_powerOrigin_2"));
        lineEdit_powerOrigin_2->setGeometry(QRect(180, 34, 113, 20));
        lineEdit_powerOrigin_2->setFont(font3);
        lineEdit_powerOrigin_2->setAlignment(Qt::AlignCenter);
        groupBox_42 = new QGroupBox(groupBox_41);
        groupBox_42->setObjectName(QStringLiteral("groupBox_42"));
        groupBox_42->setGeometry(QRect(20, 100, 431, 201));
        tableWidget_timeRespurce_4 = new QTableWidget(groupBox_42);
        if (tableWidget_timeRespurce_4->columnCount() < 3)
            tableWidget_timeRespurce_4->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        __qtablewidgetitem26->setFont(font);
        tableWidget_timeRespurce_4->setHorizontalHeaderItem(0, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        __qtablewidgetitem27->setFont(font);
        tableWidget_timeRespurce_4->setHorizontalHeaderItem(1, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        __qtablewidgetitem28->setFont(font);
        tableWidget_timeRespurce_4->setHorizontalHeaderItem(2, __qtablewidgetitem28);
        if (tableWidget_timeRespurce_4->rowCount() < 5)
            tableWidget_timeRespurce_4->setRowCount(5);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        tableWidget_timeRespurce_4->setVerticalHeaderItem(0, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        tableWidget_timeRespurce_4->setVerticalHeaderItem(1, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        tableWidget_timeRespurce_4->setVerticalHeaderItem(2, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        tableWidget_timeRespurce_4->setVerticalHeaderItem(3, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        tableWidget_timeRespurce_4->setVerticalHeaderItem(4, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        __qtablewidgetitem34->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem34->setFont(font1);
        tableWidget_timeRespurce_4->setItem(0, 0, __qtablewidgetitem34);
        QFont font4;
        font4.setFamily(QString::fromUtf8("\345\256\213\344\275\223"));
        font4.setPointSize(10);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        __qtablewidgetitem35->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem35->setFont(font4);
        tableWidget_timeRespurce_4->setItem(0, 1, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        __qtablewidgetitem36->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem36->setFont(font4);
        tableWidget_timeRespurce_4->setItem(0, 2, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        __qtablewidgetitem37->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem37->setFont(font1);
        tableWidget_timeRespurce_4->setItem(1, 0, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        __qtablewidgetitem38->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem38->setFont(font3);
        tableWidget_timeRespurce_4->setItem(1, 1, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        __qtablewidgetitem39->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem39->setFont(font4);
        tableWidget_timeRespurce_4->setItem(1, 2, __qtablewidgetitem39);
        QFont font5;
        font5.setFamily(QString::fromUtf8("\345\256\213\344\275\223"));
        font5.setPointSize(10);
        font5.setBold(true);
        font5.setWeight(75);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        __qtablewidgetitem40->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem40->setFont(font5);
        tableWidget_timeRespurce_4->setItem(2, 0, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        __qtablewidgetitem41->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem41->setFont(font4);
        tableWidget_timeRespurce_4->setItem(2, 1, __qtablewidgetitem41);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        __qtablewidgetitem42->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem42->setFont(font4);
        tableWidget_timeRespurce_4->setItem(2, 2, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        __qtablewidgetitem43->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem43->setFont(font1);
        tableWidget_timeRespurce_4->setItem(3, 0, __qtablewidgetitem43);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        __qtablewidgetitem44->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem44->setFont(font4);
        tableWidget_timeRespurce_4->setItem(3, 1, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        __qtablewidgetitem45->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem45->setFont(font4);
        tableWidget_timeRespurce_4->setItem(3, 2, __qtablewidgetitem45);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        __qtablewidgetitem46->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem46->setFont(font1);
        tableWidget_timeRespurce_4->setItem(4, 0, __qtablewidgetitem46);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        __qtablewidgetitem47->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem47->setFont(font3);
        tableWidget_timeRespurce_4->setItem(4, 1, __qtablewidgetitem47);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        __qtablewidgetitem48->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem48->setFont(font4);
        tableWidget_timeRespurce_4->setItem(4, 2, __qtablewidgetitem48);
        tableWidget_timeRespurce_4->setObjectName(QStringLiteral("tableWidget_timeRespurce_4"));
        tableWidget_timeRespurce_4->setGeometry(QRect(5, 20, 421, 178));
        tableWidget_timeRespurce_4->horizontalHeader()->setDefaultSectionSize(139);
        tableWidget_timeRespurce_4->verticalHeader()->setVisible(false);
        tableWidget_timeRespurce_4->verticalHeader()->setDefaultSectionSize(30);
        tableWidget_timeRespurce_4->verticalHeader()->setHighlightSections(true);
        tableWidget_timeRespurce_4->verticalHeader()->setMinimumSectionSize(27);
        groupBox_31 = new QGroupBox(ClientDetailInfo);
        groupBox_31->setObjectName(QStringLiteral("groupBox_31"));
        groupBox_31->setGeometry(QRect(40, 30, 461, 611));
        groupBox_27 = new QGroupBox(groupBox_31);
        groupBox_27->setObjectName(QStringLiteral("groupBox_27"));
        groupBox_27->setGeometry(QRect(20, 100, 431, 201));
        tableWidget_timeRespurce_3 = new QTableWidget(groupBox_27);
        if (tableWidget_timeRespurce_3->columnCount() < 3)
            tableWidget_timeRespurce_3->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem49 = new QTableWidgetItem();
        __qtablewidgetitem49->setFont(font);
        tableWidget_timeRespurce_3->setHorizontalHeaderItem(0, __qtablewidgetitem49);
        QTableWidgetItem *__qtablewidgetitem50 = new QTableWidgetItem();
        __qtablewidgetitem50->setFont(font);
        tableWidget_timeRespurce_3->setHorizontalHeaderItem(1, __qtablewidgetitem50);
        QTableWidgetItem *__qtablewidgetitem51 = new QTableWidgetItem();
        __qtablewidgetitem51->setFont(font);
        tableWidget_timeRespurce_3->setHorizontalHeaderItem(2, __qtablewidgetitem51);
        if (tableWidget_timeRespurce_3->rowCount() < 5)
            tableWidget_timeRespurce_3->setRowCount(5);
        QTableWidgetItem *__qtablewidgetitem52 = new QTableWidgetItem();
        tableWidget_timeRespurce_3->setVerticalHeaderItem(0, __qtablewidgetitem52);
        QTableWidgetItem *__qtablewidgetitem53 = new QTableWidgetItem();
        tableWidget_timeRespurce_3->setVerticalHeaderItem(1, __qtablewidgetitem53);
        QTableWidgetItem *__qtablewidgetitem54 = new QTableWidgetItem();
        tableWidget_timeRespurce_3->setVerticalHeaderItem(2, __qtablewidgetitem54);
        QTableWidgetItem *__qtablewidgetitem55 = new QTableWidgetItem();
        tableWidget_timeRespurce_3->setVerticalHeaderItem(3, __qtablewidgetitem55);
        QTableWidgetItem *__qtablewidgetitem56 = new QTableWidgetItem();
        tableWidget_timeRespurce_3->setVerticalHeaderItem(4, __qtablewidgetitem56);
        QTableWidgetItem *__qtablewidgetitem57 = new QTableWidgetItem();
        __qtablewidgetitem57->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem57->setFont(font1);
        tableWidget_timeRespurce_3->setItem(0, 0, __qtablewidgetitem57);
        QTableWidgetItem *__qtablewidgetitem58 = new QTableWidgetItem();
        __qtablewidgetitem58->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem58->setFont(font4);
        tableWidget_timeRespurce_3->setItem(0, 1, __qtablewidgetitem58);
        QTableWidgetItem *__qtablewidgetitem59 = new QTableWidgetItem();
        __qtablewidgetitem59->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem59->setFont(font4);
        tableWidget_timeRespurce_3->setItem(0, 2, __qtablewidgetitem59);
        QTableWidgetItem *__qtablewidgetitem60 = new QTableWidgetItem();
        __qtablewidgetitem60->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem60->setFont(font1);
        tableWidget_timeRespurce_3->setItem(1, 0, __qtablewidgetitem60);
        QTableWidgetItem *__qtablewidgetitem61 = new QTableWidgetItem();
        __qtablewidgetitem61->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem61->setFont(font3);
        tableWidget_timeRespurce_3->setItem(1, 1, __qtablewidgetitem61);
        QTableWidgetItem *__qtablewidgetitem62 = new QTableWidgetItem();
        __qtablewidgetitem62->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem62->setFont(font4);
        tableWidget_timeRespurce_3->setItem(1, 2, __qtablewidgetitem62);
        QTableWidgetItem *__qtablewidgetitem63 = new QTableWidgetItem();
        __qtablewidgetitem63->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem63->setFont(font5);
        tableWidget_timeRespurce_3->setItem(2, 0, __qtablewidgetitem63);
        QTableWidgetItem *__qtablewidgetitem64 = new QTableWidgetItem();
        __qtablewidgetitem64->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem64->setFont(font4);
        tableWidget_timeRespurce_3->setItem(2, 1, __qtablewidgetitem64);
        QTableWidgetItem *__qtablewidgetitem65 = new QTableWidgetItem();
        __qtablewidgetitem65->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem65->setFont(font4);
        tableWidget_timeRespurce_3->setItem(2, 2, __qtablewidgetitem65);
        QTableWidgetItem *__qtablewidgetitem66 = new QTableWidgetItem();
        __qtablewidgetitem66->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem66->setFont(font1);
        tableWidget_timeRespurce_3->setItem(3, 0, __qtablewidgetitem66);
        QTableWidgetItem *__qtablewidgetitem67 = new QTableWidgetItem();
        __qtablewidgetitem67->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem67->setFont(font4);
        tableWidget_timeRespurce_3->setItem(3, 1, __qtablewidgetitem67);
        QTableWidgetItem *__qtablewidgetitem68 = new QTableWidgetItem();
        __qtablewidgetitem68->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem68->setFont(font4);
        tableWidget_timeRespurce_3->setItem(3, 2, __qtablewidgetitem68);
        QTableWidgetItem *__qtablewidgetitem69 = new QTableWidgetItem();
        __qtablewidgetitem69->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem69->setFont(font1);
        tableWidget_timeRespurce_3->setItem(4, 0, __qtablewidgetitem69);
        QTableWidgetItem *__qtablewidgetitem70 = new QTableWidgetItem();
        __qtablewidgetitem70->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem70->setFont(font3);
        tableWidget_timeRespurce_3->setItem(4, 1, __qtablewidgetitem70);
        QTableWidgetItem *__qtablewidgetitem71 = new QTableWidgetItem();
        __qtablewidgetitem71->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem71->setFont(font4);
        tableWidget_timeRespurce_3->setItem(4, 2, __qtablewidgetitem71);
        tableWidget_timeRespurce_3->setObjectName(QStringLiteral("tableWidget_timeRespurce_3"));
        tableWidget_timeRespurce_3->setGeometry(QRect(5, 20, 421, 178));
        tableWidget_timeRespurce_3->horizontalHeader()->setDefaultSectionSize(139);
        tableWidget_timeRespurce_3->verticalHeader()->setVisible(false);
        tableWidget_timeRespurce_3->verticalHeader()->setDefaultSectionSize(30);
        tableWidget_timeRespurce_3->verticalHeader()->setHighlightSections(true);
        tableWidget_timeRespurce_3->verticalHeader()->setMinimumSectionSize(27);
        groupBox_32 = new QGroupBox(groupBox_31);
        groupBox_32->setObjectName(QStringLiteral("groupBox_32"));
        groupBox_32->setGeometry(QRect(20, 310, 431, 171));
        tableWidget_RbClockStatus_1 = new QTableWidget(groupBox_32);
        if (tableWidget_RbClockStatus_1->columnCount() < 3)
            tableWidget_RbClockStatus_1->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem72 = new QTableWidgetItem();
        __qtablewidgetitem72->setFont(font);
        tableWidget_RbClockStatus_1->setHorizontalHeaderItem(0, __qtablewidgetitem72);
        QTableWidgetItem *__qtablewidgetitem73 = new QTableWidgetItem();
        __qtablewidgetitem73->setFont(font);
        tableWidget_RbClockStatus_1->setHorizontalHeaderItem(1, __qtablewidgetitem73);
        QTableWidgetItem *__qtablewidgetitem74 = new QTableWidgetItem();
        __qtablewidgetitem74->setFont(font);
        tableWidget_RbClockStatus_1->setHorizontalHeaderItem(2, __qtablewidgetitem74);
        if (tableWidget_RbClockStatus_1->rowCount() < 4)
            tableWidget_RbClockStatus_1->setRowCount(4);
        QTableWidgetItem *__qtablewidgetitem75 = new QTableWidgetItem();
        tableWidget_RbClockStatus_1->setVerticalHeaderItem(0, __qtablewidgetitem75);
        QTableWidgetItem *__qtablewidgetitem76 = new QTableWidgetItem();
        tableWidget_RbClockStatus_1->setVerticalHeaderItem(1, __qtablewidgetitem76);
        QTableWidgetItem *__qtablewidgetitem77 = new QTableWidgetItem();
        tableWidget_RbClockStatus_1->setVerticalHeaderItem(2, __qtablewidgetitem77);
        QTableWidgetItem *__qtablewidgetitem78 = new QTableWidgetItem();
        tableWidget_RbClockStatus_1->setVerticalHeaderItem(3, __qtablewidgetitem78);
        QTableWidgetItem *__qtablewidgetitem79 = new QTableWidgetItem();
        __qtablewidgetitem79->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem79->setFont(font1);
        tableWidget_RbClockStatus_1->setItem(0, 0, __qtablewidgetitem79);
        QTableWidgetItem *__qtablewidgetitem80 = new QTableWidgetItem();
        tableWidget_RbClockStatus_1->setItem(0, 1, __qtablewidgetitem80);
        QTableWidgetItem *__qtablewidgetitem81 = new QTableWidgetItem();
        tableWidget_RbClockStatus_1->setItem(0, 2, __qtablewidgetitem81);
        QTableWidgetItem *__qtablewidgetitem82 = new QTableWidgetItem();
        __qtablewidgetitem82->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem82->setFont(font2);
        tableWidget_RbClockStatus_1->setItem(1, 0, __qtablewidgetitem82);
        QTableWidgetItem *__qtablewidgetitem83 = new QTableWidgetItem();
        tableWidget_RbClockStatus_1->setItem(1, 1, __qtablewidgetitem83);
        QTableWidgetItem *__qtablewidgetitem84 = new QTableWidgetItem();
        tableWidget_RbClockStatus_1->setItem(1, 2, __qtablewidgetitem84);
        QTableWidgetItem *__qtablewidgetitem85 = new QTableWidgetItem();
        __qtablewidgetitem85->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem85->setFont(font1);
        tableWidget_RbClockStatus_1->setItem(2, 0, __qtablewidgetitem85);
        QTableWidgetItem *__qtablewidgetitem86 = new QTableWidgetItem();
        tableWidget_RbClockStatus_1->setItem(2, 1, __qtablewidgetitem86);
        QTableWidgetItem *__qtablewidgetitem87 = new QTableWidgetItem();
        tableWidget_RbClockStatus_1->setItem(2, 2, __qtablewidgetitem87);
        QTableWidgetItem *__qtablewidgetitem88 = new QTableWidgetItem();
        __qtablewidgetitem88->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem88->setFont(font1);
        tableWidget_RbClockStatus_1->setItem(3, 0, __qtablewidgetitem88);
        tableWidget_RbClockStatus_1->setObjectName(QStringLiteral("tableWidget_RbClockStatus_1"));
        tableWidget_RbClockStatus_1->setGeometry(QRect(6, 20, 421, 148));
        tableWidget_RbClockStatus_1->horizontalHeader()->setCascadingSectionResizes(true);
        tableWidget_RbClockStatus_1->horizontalHeader()->setDefaultSectionSize(139);
        tableWidget_RbClockStatus_1->verticalHeader()->setVisible(false);
        tableWidget_RbClockStatus_1->verticalHeader()->setCascadingSectionResizes(false);
        tableWidget_RbClockStatus_1->verticalHeader()->setHighlightSections(false);
        groupBox_40 = new QGroupBox(groupBox_31);
        groupBox_40->setObjectName(QStringLiteral("groupBox_40"));
        groupBox_40->setGeometry(QRect(20, 490, 431, 111));
        tableWidget_cardBoardStatus_1 = new QTableWidget(groupBox_40);
        if (tableWidget_cardBoardStatus_1->columnCount() < 3)
            tableWidget_cardBoardStatus_1->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem89 = new QTableWidgetItem();
        __qtablewidgetitem89->setFont(font);
        tableWidget_cardBoardStatus_1->setHorizontalHeaderItem(0, __qtablewidgetitem89);
        QTableWidgetItem *__qtablewidgetitem90 = new QTableWidgetItem();
        __qtablewidgetitem90->setFont(font);
        tableWidget_cardBoardStatus_1->setHorizontalHeaderItem(1, __qtablewidgetitem90);
        QTableWidgetItem *__qtablewidgetitem91 = new QTableWidgetItem();
        __qtablewidgetitem91->setFont(font);
        tableWidget_cardBoardStatus_1->setHorizontalHeaderItem(2, __qtablewidgetitem91);
        if (tableWidget_cardBoardStatus_1->rowCount() < 2)
            tableWidget_cardBoardStatus_1->setRowCount(2);
        QTableWidgetItem *__qtablewidgetitem92 = new QTableWidgetItem();
        tableWidget_cardBoardStatus_1->setVerticalHeaderItem(0, __qtablewidgetitem92);
        QTableWidgetItem *__qtablewidgetitem93 = new QTableWidgetItem();
        tableWidget_cardBoardStatus_1->setVerticalHeaderItem(1, __qtablewidgetitem93);
        QTableWidgetItem *__qtablewidgetitem94 = new QTableWidgetItem();
        __qtablewidgetitem94->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem94->setFont(font1);
        tableWidget_cardBoardStatus_1->setItem(0, 0, __qtablewidgetitem94);
        QTableWidgetItem *__qtablewidgetitem95 = new QTableWidgetItem();
        tableWidget_cardBoardStatus_1->setItem(0, 1, __qtablewidgetitem95);
        QTableWidgetItem *__qtablewidgetitem96 = new QTableWidgetItem();
        tableWidget_cardBoardStatus_1->setItem(0, 2, __qtablewidgetitem96);
        QTableWidgetItem *__qtablewidgetitem97 = new QTableWidgetItem();
        __qtablewidgetitem97->setTextAlignment(Qt::AlignCenter);
        __qtablewidgetitem97->setFont(font1);
        tableWidget_cardBoardStatus_1->setItem(1, 0, __qtablewidgetitem97);
        tableWidget_cardBoardStatus_1->setObjectName(QStringLiteral("tableWidget_cardBoardStatus_1"));
        tableWidget_cardBoardStatus_1->setGeometry(QRect(6, 20, 421, 88));
        tableWidget_cardBoardStatus_1->horizontalHeader()->setDefaultSectionSize(139);
        tableWidget_cardBoardStatus_1->verticalHeader()->setVisible(false);
        groupBox_39 = new QGroupBox(groupBox_31);
        groupBox_39->setObjectName(QStringLiteral("groupBox_39"));
        groupBox_39->setGeometry(QRect(20, 20, 431, 61));
        label_11 = new QLabel(groupBox_39);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(70, 7, 111, 21));
        label_11->setFont(font1);
        label_11->setTextFormat(Qt::AutoText);
        label_11->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_12 = new QLabel(groupBox_39);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(70, 34, 111, 21));
        label_12->setFont(font1);
        label_12->setTextFormat(Qt::AutoText);
        label_12->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEdit_powerStatus_1 = new QLineEdit(groupBox_39);
        lineEdit_powerStatus_1->setObjectName(QStringLiteral("lineEdit_powerStatus_1"));
        lineEdit_powerStatus_1->setGeometry(QRect(180, 7, 113, 20));
        lineEdit_powerStatus_1->setFont(font3);
        lineEdit_powerStatus_1->setAlignment(Qt::AlignCenter);
        lineEdit_powerOrigin_1 = new QLineEdit(groupBox_39);
        lineEdit_powerOrigin_1->setObjectName(QStringLiteral("lineEdit_powerOrigin_1"));
        lineEdit_powerOrigin_1->setGeometry(QRect(180, 34, 113, 20));
        lineEdit_powerOrigin_1->setFont(font3);
        lineEdit_powerOrigin_1->setAlignment(Qt::AlignCenter);
        pushButton = new QPushButton(ClientDetailInfo);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(918, 5, 75, 27));
        label = new QLabel(ClientDetailInfo);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(420, 6, 151, 22));
        label->setFont(font1);
        label->setAlignment(Qt::AlignCenter);

        retranslateUi(ClientDetailInfo);

        QMetaObject::connectSlotsByName(ClientDetailInfo);
    } // setupUi

    void retranslateUi(QWidget *ClientDetailInfo)
    {
        ClientDetailInfo->setWindowTitle(QApplication::translate("ClientDetailInfo", "Form", Q_NULLPTR));
        groupBox_41->setTitle(QApplication::translate("ClientDetailInfo", "\344\270\273\346\234\2722\347\212\266\346\200\201", Q_NULLPTR));
        groupBox_43->setTitle(QApplication::translate("ClientDetailInfo", "\351\223\267\351\222\237\347\212\266\346\200\201", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem = tableWidget_RbClockStatus_2->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("ClientDetailInfo", "\351\241\271\347\233\256", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget_RbClockStatus_2->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("ClientDetailInfo", "\351\223\267\351\222\2371", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget_RbClockStatus_2->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QApplication::translate("ClientDetailInfo", "\351\223\267\351\222\2372", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidget_RbClockStatus_2->verticalHeaderItem(0);
        ___qtablewidgetitem3->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidget_RbClockStatus_2->verticalHeaderItem(1);
        ___qtablewidgetitem4->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidget_RbClockStatus_2->verticalHeaderItem(2);
        ___qtablewidgetitem5->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidget_RbClockStatus_2->verticalHeaderItem(3);
        ___qtablewidgetitem6->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));

        const bool __sortingEnabled = tableWidget_RbClockStatus_2->isSortingEnabled();
        tableWidget_RbClockStatus_2->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem7 = tableWidget_RbClockStatus_2->item(0, 0);
        ___qtablewidgetitem7->setText(QApplication::translate("ClientDetailInfo", "\346\231\266\346\214\257\351\224\201\345\256\232", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidget_RbClockStatus_2->item(1, 0);
        ___qtablewidgetitem8->setText(QApplication::translate("ClientDetailInfo", "\347\263\273\347\273\237\351\224\201\345\256\232", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidget_RbClockStatus_2->item(2, 0);
        ___qtablewidgetitem9->setText(QApplication::translate("ClientDetailInfo", "\347\236\254\346\227\266\346\227\266\345\267\256", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidget_RbClockStatus_2->item(3, 0);
        ___qtablewidgetitem10->setText(QApplication::translate("ClientDetailInfo", "\346\270\251\345\272\246", Q_NULLPTR));
        tableWidget_RbClockStatus_2->setSortingEnabled(__sortingEnabled);

        groupBox_44->setTitle(QApplication::translate("ClientDetailInfo", "\346\235\277\345\215\241\347\212\266\346\200\201", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidget_cardBoardStatus_2->horizontalHeaderItem(0);
        ___qtablewidgetitem11->setText(QApplication::translate("ClientDetailInfo", "\346\235\277\345\215\241", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem12 = tableWidget_cardBoardStatus_2->horizontalHeaderItem(1);
        ___qtablewidgetitem12->setText(QApplication::translate("ClientDetailInfo", "\350\276\223\345\207\272\347\212\266\346\200\201", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidget_cardBoardStatus_2->horizontalHeaderItem(2);
        ___qtablewidgetitem13->setText(QApplication::translate("ClientDetailInfo", "\346\270\251\345\272\246", Q_NULLPTR));

        const bool __sortingEnabled1 = tableWidget_cardBoardStatus_2->isSortingEnabled();
        tableWidget_cardBoardStatus_2->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem14 = tableWidget_cardBoardStatus_2->item(0, 0);
        ___qtablewidgetitem14->setText(QApplication::translate("ClientDetailInfo", "\346\240\207\351\242\221\346\235\277\345\215\241", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidget_cardBoardStatus_2->item(1, 0);
        ___qtablewidgetitem15->setText(QApplication::translate("ClientDetailInfo", "\344\270\262\345\217\243\346\235\277\345\215\241", Q_NULLPTR));
        tableWidget_cardBoardStatus_2->setSortingEnabled(__sortingEnabled1);

        groupBox_45->setTitle(QString());
        label_13->setText(QApplication::translate("ClientDetailInfo", "\347\224\265\346\272\220\347\212\266\346\200\201", Q_NULLPTR));
        label_14->setText(QApplication::translate("ClientDetailInfo", "\347\224\250\347\224\265\346\235\245\346\272\220", Q_NULLPTR));
        groupBox_42->setTitle(QApplication::translate("ClientDetailInfo", "\346\227\266\351\227\264\346\272\220\347\212\266\346\200\201", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem16 = tableWidget_timeRespurce_4->horizontalHeaderItem(0);
        ___qtablewidgetitem16->setText(QApplication::translate("ClientDetailInfo", "\346\227\266\351\227\264\346\272\220", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem17 = tableWidget_timeRespurce_4->horizontalHeaderItem(1);
        ___qtablewidgetitem17->setText(QApplication::translate("ClientDetailInfo", "\346\230\257\345\220\246\346\234\211\346\225\210", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem18 = tableWidget_timeRespurce_4->horizontalHeaderItem(2);
        ___qtablewidgetitem18->setText(QApplication::translate("ClientDetailInfo", "\346\230\257\345\220\246\344\275\277\347\224\250", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem19 = tableWidget_timeRespurce_4->verticalHeaderItem(0);
        ___qtablewidgetitem19->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem20 = tableWidget_timeRespurce_4->verticalHeaderItem(1);
        ___qtablewidgetitem20->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem21 = tableWidget_timeRespurce_4->verticalHeaderItem(2);
        ___qtablewidgetitem21->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem22 = tableWidget_timeRespurce_4->verticalHeaderItem(3);
        ___qtablewidgetitem22->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem23 = tableWidget_timeRespurce_4->verticalHeaderItem(4);
        ___qtablewidgetitem23->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));

        const bool __sortingEnabled2 = tableWidget_timeRespurce_4->isSortingEnabled();
        tableWidget_timeRespurce_4->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem24 = tableWidget_timeRespurce_4->item(0, 0);
        ___qtablewidgetitem24->setText(QApplication::translate("ClientDetailInfo", "\345\214\227\346\226\227", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem25 = tableWidget_timeRespurce_4->item(0, 1);
        ___qtablewidgetitem25->setText(QApplication::translate("ClientDetailInfo", "\346\234\211\346\225\210", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem26 = tableWidget_timeRespurce_4->item(0, 2);
        ___qtablewidgetitem26->setText(QApplication::translate("ClientDetailInfo", "\346\255\243\345\234\250\344\275\277\347\224\250", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem27 = tableWidget_timeRespurce_4->item(1, 0);
        ___qtablewidgetitem27->setText(QApplication::translate("ClientDetailInfo", "IRIG-B", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem28 = tableWidget_timeRespurce_4->item(1, 1);
        ___qtablewidgetitem28->setText(QApplication::translate("ClientDetailInfo", "\346\234\211\346\225\210", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem29 = tableWidget_timeRespurce_4->item(1, 2);
        ___qtablewidgetitem29->setText(QApplication::translate("ClientDetailInfo", "\346\234\252\344\275\277\347\224\250", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem30 = tableWidget_timeRespurce_4->item(2, 0);
        ___qtablewidgetitem30->setText(QApplication::translate("ClientDetailInfo", "GPS/GLONASS", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem31 = tableWidget_timeRespurce_4->item(2, 1);
        ___qtablewidgetitem31->setText(QApplication::translate("ClientDetailInfo", "\346\234\211\346\225\210", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem32 = tableWidget_timeRespurce_4->item(2, 2);
        ___qtablewidgetitem32->setText(QApplication::translate("ClientDetailInfo", "\346\234\252\344\275\277\347\224\250", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem33 = tableWidget_timeRespurce_4->item(3, 0);
        ___qtablewidgetitem33->setText(QApplication::translate("ClientDetailInfo", "\347\237\255\346\263\242", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem34 = tableWidget_timeRespurce_4->item(3, 1);
        ___qtablewidgetitem34->setText(QApplication::translate("ClientDetailInfo", "\346\227\240\346\225\210", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem35 = tableWidget_timeRespurce_4->item(3, 2);
        ___qtablewidgetitem35->setText(QApplication::translate("ClientDetailInfo", "\346\234\252\344\275\277\347\224\250", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem36 = tableWidget_timeRespurce_4->item(4, 0);
        ___qtablewidgetitem36->setText(QApplication::translate("ClientDetailInfo", "\351\225\277\346\263\242", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem37 = tableWidget_timeRespurce_4->item(4, 1);
        ___qtablewidgetitem37->setText(QApplication::translate("ClientDetailInfo", "\346\227\240\346\225\210", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem38 = tableWidget_timeRespurce_4->item(4, 2);
        ___qtablewidgetitem38->setText(QApplication::translate("ClientDetailInfo", "\346\234\252\344\275\277\347\224\250", Q_NULLPTR));
        tableWidget_timeRespurce_4->setSortingEnabled(__sortingEnabled2);

        groupBox_31->setTitle(QApplication::translate("ClientDetailInfo", "\344\270\273\346\234\2721\347\212\266\346\200\201", Q_NULLPTR));
        groupBox_27->setTitle(QApplication::translate("ClientDetailInfo", "\346\227\266\351\227\264\346\272\220\347\212\266\346\200\201", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem39 = tableWidget_timeRespurce_3->horizontalHeaderItem(0);
        ___qtablewidgetitem39->setText(QApplication::translate("ClientDetailInfo", "\346\227\266\351\227\264\346\272\220", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem40 = tableWidget_timeRespurce_3->horizontalHeaderItem(1);
        ___qtablewidgetitem40->setText(QApplication::translate("ClientDetailInfo", "\346\230\257\345\220\246\346\234\211\346\225\210", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem41 = tableWidget_timeRespurce_3->horizontalHeaderItem(2);
        ___qtablewidgetitem41->setText(QApplication::translate("ClientDetailInfo", "\346\230\257\345\220\246\344\275\277\347\224\250", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem42 = tableWidget_timeRespurce_3->verticalHeaderItem(0);
        ___qtablewidgetitem42->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem43 = tableWidget_timeRespurce_3->verticalHeaderItem(1);
        ___qtablewidgetitem43->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem44 = tableWidget_timeRespurce_3->verticalHeaderItem(2);
        ___qtablewidgetitem44->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem45 = tableWidget_timeRespurce_3->verticalHeaderItem(3);
        ___qtablewidgetitem45->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem46 = tableWidget_timeRespurce_3->verticalHeaderItem(4);
        ___qtablewidgetitem46->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));

        const bool __sortingEnabled3 = tableWidget_timeRespurce_3->isSortingEnabled();
        tableWidget_timeRespurce_3->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem47 = tableWidget_timeRespurce_3->item(0, 0);
        ___qtablewidgetitem47->setText(QApplication::translate("ClientDetailInfo", "\345\214\227\346\226\227", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem48 = tableWidget_timeRespurce_3->item(0, 1);
        ___qtablewidgetitem48->setText(QApplication::translate("ClientDetailInfo", "\346\234\211\346\225\210", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem49 = tableWidget_timeRespurce_3->item(0, 2);
        ___qtablewidgetitem49->setText(QApplication::translate("ClientDetailInfo", "\346\255\243\345\234\250\344\275\277\347\224\250", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem50 = tableWidget_timeRespurce_3->item(1, 0);
        ___qtablewidgetitem50->setText(QApplication::translate("ClientDetailInfo", "IRIG-B", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem51 = tableWidget_timeRespurce_3->item(1, 1);
        ___qtablewidgetitem51->setText(QApplication::translate("ClientDetailInfo", "\346\234\211\346\225\210", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem52 = tableWidget_timeRespurce_3->item(1, 2);
        ___qtablewidgetitem52->setText(QApplication::translate("ClientDetailInfo", "\346\234\252\344\275\277\347\224\250", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem53 = tableWidget_timeRespurce_3->item(2, 0);
        ___qtablewidgetitem53->setText(QApplication::translate("ClientDetailInfo", "GPS/GLONASS", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem54 = tableWidget_timeRespurce_3->item(2, 1);
        ___qtablewidgetitem54->setText(QApplication::translate("ClientDetailInfo", "\346\234\211\346\225\210", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem55 = tableWidget_timeRespurce_3->item(2, 2);
        ___qtablewidgetitem55->setText(QApplication::translate("ClientDetailInfo", "\346\234\252\344\275\277\347\224\250", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem56 = tableWidget_timeRespurce_3->item(3, 0);
        ___qtablewidgetitem56->setText(QApplication::translate("ClientDetailInfo", "\347\237\255\346\263\242", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem57 = tableWidget_timeRespurce_3->item(3, 1);
        ___qtablewidgetitem57->setText(QApplication::translate("ClientDetailInfo", "\346\227\240\346\225\210", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem58 = tableWidget_timeRespurce_3->item(3, 2);
        ___qtablewidgetitem58->setText(QApplication::translate("ClientDetailInfo", "\346\234\252\344\275\277\347\224\250", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem59 = tableWidget_timeRespurce_3->item(4, 0);
        ___qtablewidgetitem59->setText(QApplication::translate("ClientDetailInfo", "\351\225\277\346\263\242", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem60 = tableWidget_timeRespurce_3->item(4, 1);
        ___qtablewidgetitem60->setText(QApplication::translate("ClientDetailInfo", "\346\227\240\346\225\210", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem61 = tableWidget_timeRespurce_3->item(4, 2);
        ___qtablewidgetitem61->setText(QApplication::translate("ClientDetailInfo", "\346\234\252\344\275\277\347\224\250", Q_NULLPTR));
        tableWidget_timeRespurce_3->setSortingEnabled(__sortingEnabled3);

        groupBox_32->setTitle(QApplication::translate("ClientDetailInfo", "\351\223\267\351\222\237\347\212\266\346\200\201", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem62 = tableWidget_RbClockStatus_1->horizontalHeaderItem(0);
        ___qtablewidgetitem62->setText(QApplication::translate("ClientDetailInfo", "\351\241\271\347\233\256", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem63 = tableWidget_RbClockStatus_1->horizontalHeaderItem(1);
        ___qtablewidgetitem63->setText(QApplication::translate("ClientDetailInfo", "\351\223\267\351\222\2371", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem64 = tableWidget_RbClockStatus_1->horizontalHeaderItem(2);
        ___qtablewidgetitem64->setText(QApplication::translate("ClientDetailInfo", "\351\223\267\351\222\2372", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem65 = tableWidget_RbClockStatus_1->verticalHeaderItem(0);
        ___qtablewidgetitem65->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem66 = tableWidget_RbClockStatus_1->verticalHeaderItem(1);
        ___qtablewidgetitem66->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem67 = tableWidget_RbClockStatus_1->verticalHeaderItem(2);
        ___qtablewidgetitem67->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem68 = tableWidget_RbClockStatus_1->verticalHeaderItem(3);
        ___qtablewidgetitem68->setText(QApplication::translate("ClientDetailInfo", "\346\226\260\345\273\272\350\241\214", Q_NULLPTR));

        const bool __sortingEnabled4 = tableWidget_RbClockStatus_1->isSortingEnabled();
        tableWidget_RbClockStatus_1->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem69 = tableWidget_RbClockStatus_1->item(0, 0);
        ___qtablewidgetitem69->setText(QApplication::translate("ClientDetailInfo", "\346\231\266\346\214\257\351\224\201\345\256\232", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem70 = tableWidget_RbClockStatus_1->item(1, 0);
        ___qtablewidgetitem70->setText(QApplication::translate("ClientDetailInfo", "\347\263\273\347\273\237\351\224\201\345\256\232", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem71 = tableWidget_RbClockStatus_1->item(2, 0);
        ___qtablewidgetitem71->setText(QApplication::translate("ClientDetailInfo", "\347\236\254\346\227\266\346\227\266\345\267\256", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem72 = tableWidget_RbClockStatus_1->item(3, 0);
        ___qtablewidgetitem72->setText(QApplication::translate("ClientDetailInfo", "\346\270\251\345\272\246", Q_NULLPTR));
        tableWidget_RbClockStatus_1->setSortingEnabled(__sortingEnabled4);

        groupBox_40->setTitle(QApplication::translate("ClientDetailInfo", "\346\235\277\345\215\241\347\212\266\346\200\201", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem73 = tableWidget_cardBoardStatus_1->horizontalHeaderItem(0);
        ___qtablewidgetitem73->setText(QApplication::translate("ClientDetailInfo", "\346\235\277\345\215\241", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem74 = tableWidget_cardBoardStatus_1->horizontalHeaderItem(1);
        ___qtablewidgetitem74->setText(QApplication::translate("ClientDetailInfo", "\350\276\223\345\207\272\347\212\266\346\200\201", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem75 = tableWidget_cardBoardStatus_1->horizontalHeaderItem(2);
        ___qtablewidgetitem75->setText(QApplication::translate("ClientDetailInfo", "\346\270\251\345\272\246", Q_NULLPTR));

        const bool __sortingEnabled5 = tableWidget_cardBoardStatus_1->isSortingEnabled();
        tableWidget_cardBoardStatus_1->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem76 = tableWidget_cardBoardStatus_1->item(0, 0);
        ___qtablewidgetitem76->setText(QApplication::translate("ClientDetailInfo", "\346\240\207\351\242\221\346\235\277\345\215\241", Q_NULLPTR));
        QTableWidgetItem *___qtablewidgetitem77 = tableWidget_cardBoardStatus_1->item(1, 0);
        ___qtablewidgetitem77->setText(QApplication::translate("ClientDetailInfo", "\344\270\262\345\217\243\346\235\277\345\215\241", Q_NULLPTR));
        tableWidget_cardBoardStatus_1->setSortingEnabled(__sortingEnabled5);

        groupBox_39->setTitle(QString());
        label_11->setText(QApplication::translate("ClientDetailInfo", "\347\224\265\346\272\220\347\212\266\346\200\201", Q_NULLPTR));
        label_12->setText(QApplication::translate("ClientDetailInfo", "\347\224\250\347\224\265\346\235\245\346\272\220", Q_NULLPTR));
        pushButton->setText(QApplication::translate("ClientDetailInfo", "\350\277\224\345\233\236", Q_NULLPTR));
        label->setText(QApplication::translate("ClientDetailInfo", "\345\210\206\346\234\272\345\220\215\347\247\260\346\230\276\347\244\272", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class ClientDetailInfo: public Ui_ClientDetailInfo {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CLIENTDETAILINFO_H
